### PR TITLE
Resolve #14 - provide ivar bed and indexed ref file.

### LINKED ISSUE #14: Provide own ivar bed file and aligner ref prefix
In a production environment, it is preferable to have a known fixed version of the bed file to be used with ivar, and to not waste a step of the workflow creating an ivar-compatible version every time.

Likewise, it is preferable to index the reference once and not repeat this every time the workflow is run.

### PR DESCRIPTION
**Pull request by sb10**
Also fixes cram-related config warning.
Also adds `--cache` option.

### CODE REVIEW

**Comment by sb10** [comment]
To use, you either do something like:

```
nextflow run ncov2019-artic-nf -profile conda --ivarBed  ivar.bed --alignerRefPrefix ref/nCoV-2019.reference.fasta --illumina --directory fastq --outdir quick --cache cache
```

Or you set the options in your own config file.

**Comment by JonKeatley112** [comment]
Can you give a little detail on expected behaviour please?

What happens if only `--ivarBed` or  `--alignerRefPrefix` is used?

What is the function of `--cache`?

**Comment by roamato** [comment]
I believe this is one for @sb10

**Comment by sb10** [comment]
> What happens if only `--ivarBed` or `--alignerRefPrefix` is used?

The docs in the conf file state that both must be supplied. If only 1, nothing happens. I'll improve this to fail with an error if only 1 is supplied.

> What is the function of `--cache`?

Makes it easier to set conda.cacheDir or singularity.cachDir. I don't know if this is necessary; is there already and easy way to set these at run time?

**Comment by sb10** [comment]
This is currently broken by upstream changes, I'm fixing now...

**Comment by sb10** [comment]
Now fixed, please test.

**Comment by JonKeatley112** [comment]
As this workflow is being used in an environment I can not test I recommend that someone else review it

**Review by mgcam — APPROVED** [review]
This version was successfully used last week to produce files for upload

**Pull request merged**
